POST http://localhost:2525/imposters

{
  "port": 4546,
  "protocol": "http",
  "stubs": [{
    "responses": [
      { "is": { "statusCode": 400 ,"Nome": "Diogo" }}
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/test",
            "method": "POST",
            "headers": { "Content-Type": "application/json" }
          }
        },
        {
          "not": {
            "contains": { "body": "requiredField" },
            "caseSensitive": true
          }
        }
      ]
    }]
  }]
}
