POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4551,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/users"
          }
        },
        {
          "equals": {
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "equals": {
            "body": {
              "email": "exists@example.com"
            }
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 409,
            "headers": {
              "Content-Type": "application/json"
            },
            "body": {
              "error": "email_exists",
              "message": "Email already exists"
            }
          }
        }
      ]
    }
  ]
}